using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IoT.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialIoTModel9 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AutoCloseSettings");

            migrationBuilder.DropColumn(
                name: "ExecuteAtUtc",
                table: "DeviceCommands");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "DeviceCommands");

            migrationBuilder.RenameColumn(
                name: "IssuedAtUtc",
                table: "DeviceCommands",
                newName: "CreatedAtUtc");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "CreatedAtUtc",
                table: "DeviceCommands",
                newName: "IssuedAtUtc");

            migrationBuilder.AddColumn<DateTime>(
                name: "ExecuteAtUtc",
                table: "DeviceCommands",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "DeviceCommands",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "AutoCloseSettings",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AfterSeconds = table.Column<int>(type: "int", nullable: false),
                    ClosePercentage = table.Column<int>(type: "int", nullable: true),
                    DeviceId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Enabled = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AutoCloseSettings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AutoCloseSettings_Devices_DeviceId",
                        column: x => x.DeviceId,
                        principalTable: "Devices",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AutoCloseSettings_DeviceId",
                table: "AutoCloseSettings",
                column: "DeviceId",
                unique: true);
        }
    }
}
